replicaCount: 2

image:
  repository: httpd
  tag: "2.4"

host: apache.formazione.local
ingressClassName: nginx

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
